### ISSUE TITLE
Create scraper for NYS DEP site

### ISSUE THREAD

**Issue by dominicmauro** [ProgressiveHackNight/take-back-day-data-scraping#4]
http://www.dec.ny.gov/gmk/index.html?url=http://www.dec.ny.gov/maps/gmnysmeddropbox.kmz

Can probably just parse the file here: http://www.dec.ny.gov/maps/gmnysmeddropbox.kmz

**Comment by designandcode** [comment]
824bf52130577c0e7d89b318f15d48c35b967ed5
