### ISSUE TITLE
Create list of columns in the scraped data

### ISSUE THREAD

**Issue by dominicmauro** [ProgressiveHackNight/take-back-day-data-scraping#6]

**Comment by designandcode** [comment]
[{
 “Location”: “Albany Police Department”,
 “Street Address”: “165 Henry Johnson Blvd”,
 “City”: “Albany”,
 “Zip”: “12210",
 “County”: “Albany”,
 “Phone”: “(518) 462-8013",
 “Hours”: “Available 24 hours a day, 7 days a week.“,
 “Note”: “Accepted: any prescription or over-the-counter medications. Not accepted: needles.“,
 “Latitude”: “42.662809",
 “Longitude”: “-73.760516",
 “Type”: “Police”
}, …]
